### PR TITLE
VM Options support for Notebooks and fixed Enable Preview Option

### LINKED ISSUE #539: Java Notebooks Crash - Using jdk.notebook.enablePreview as true with Early Access Java Version 26
### Issue Summary

Java Notebooks - Using  jdk.notebook.enablePreview as true with Early Access Java Version Crashes Notebooks

### Issue Detail

Use Case - Use [Java Notebook](https://marketplace.visualstudio.com/items?itemName=Oracle.oracle-java) over a Java Early Access binary such as [JDK 26](https://jdk.java.net/26/) with enablePreview flag enabled and jdk.advanced.disable.nbjavac as true

### VS Code [Extension](https://marketplace.visualstudio.com/items?itemName=Oracle.oracle-java) Version

```
Identifier oracle.oracle-java
Version 25.0.0
Last Updated 2 weeks ago
Size 301.55MB
```

### [Java](https://jdk.java.net/26/) Version

```
$ java --version
openjdk 26-ea 2026-03-17
OpenJDK Runtime Environment (build 26-ea+29-2803)
OpenJDK 64-Bit Server VM (build 26-ea+29-2803, mixed mode, sharing)
```

### VS Code Configuration

```
"jdk.jdkhome": "/Library/Java/JavaVirtualMachines/jdk-26.jdk/Contents/Home",
"jdk.notebook.enablePreview": true,
"jdk.advanced.disable.nbjavac": true,
```

### Error Stack

```
2025-12-27 18:05:31.470 [error] Error: error: invalid source release: 26-ea
	at handleResponse (/Users/<username>/.vscode/extensions/oracle.oracle-java-25.0.0/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)
	at handleMessage (/Users/<username>/.vscode/extensions/oracle.oracle-java-25.0.0/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)
	at processMessageQueue (/Users/<username>/.vscode/extensions/oracle.oracle-java-25.0.0/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)
	at Immediate.<anonymous> (/Users/<username>/.vscode/extensions/oracle.oracle-java-25.0.0/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)
	at process.processImmediate (node:internal/timers:485:21) jdk.jshell.execute.cell {"value":"Oracle.oracle-java","_lower":"oracle.oracle-java"}
```

### PR DESCRIPTION
**Pull request by Achal1607**
Added VM Options config for notebooks, fixed enable preview failing with EA versions bug and added logger for knowing with which options the kernel is being launched.

Closes #539

### CODE REVIEW

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java [hunk 1]
```diff
@@ -154,7 +165,8 @@ private CompletableFuture<Void> initializeConfigs() {
     }
 
     public String getJdkVersion() {
-        return System.getProperty("java.version").split("\\.")[0];
+        // As per JEP-223
+        return System.getProperty("java.specification.version");
```
Comment (sid-srini) [inline nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java:186]: Would it be possible to query this property value from the `JavaPlatformProvider.getSystemProperties()`? That may allow reading the version of the project jdkhome instead of the extension runtime.

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookSessionManager.java [hunk 2]
```diff
@@ -94,12 +94,15 @@ private JShell jshellBuildWithProject(String notebookUri, Project prj, JshellStr
         List<String> compilerOptions = getCompilerOptions(prj);
         List<String> remoteOptions = getRemoteVmOptions(prj);
         setSystemPropertiesForRemoteVm(remoteOptions, notebookUri);
-
+
```
Comment (sid-srini) [inline nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookSessionManager.java]: nit: spurious change; may be removed.

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookSessionManager.java [hunk 3]
```diff
@@ -94,12 +94,15 @@ private JShell jshellBuildWithProject(String notebookUri, Project prj, JshellStr
...
-
+        
         JShell.Builder builder = JShell.builder()
                 .out(streamsHandler.getPrintOutStream())
                 .err(streamsHandler.getPrintErrStream())
                 .in(streamsHandler.getInputStream());
 
+        LOG.log(Level.INFO, "Initializing Notebook kernel for {0}", notebookUri);
+        LOG.log(Level.INFO, "Compiler options being passed: {0}", compilerOptions.toString());
+        LOG.log(Level.INFO, "VM Options being passed to notebook kernel: {0}", remoteOptions.toString());
```
Comment (sid-srini) [inline nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookSessionManager.java]: nit: It may be better to leave this at a `FINE` log level, so that this information is logged only when verbosity is explicitly requested by the user. Also, the `.toString()` need not be added to the message arguments.

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java [hunk 4]
```diff
@@ -76,6 +78,10 @@ public JsonObject getNotebookProjectMapping() {
         return notebookProjectMapping;
     }
 
+    public List<String> getNotebookVmOptions() {
+        return notebookVmOptions;
```
Comment (sid-srini) [inline nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java:85]: nit: Its usages appear to suggest that this is expected to return a non-null value. If so, it should be ensured in the implementation or/and a clear annotation added for it.

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java [hunk 5]
```diff
@@ -39,12 +39,14 @@ public class NotebookConfigs {
...
         "notebook.implicitImports",
-        "notebook.projects.mapping"};
+        "notebook.projects.mapping",
+        "notebook.vmOptions"};
     private volatile String classPath = null;
     private volatile String modulePath = null;
     private volatile String addModules = null;
     private volatile boolean enablePreview = false;
     private volatile JsonObject notebookProjectMapping = new JsonObject();
+    private volatile List<String> notebookVmOptions = new ArrayList<>();
```
Comment (sid-srini) [inline nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java]: nit: It may be better to treat this as an unmodifiable List and thus initialize it with a `Collections.emptyList()` instead.

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java [hunk 6]
```diff
@@ -145,6 +151,11 @@ private CompletableFuture<Void> initializeConfigs() {
                     if (notebookProjectMappingConfig != null) {
                         notebookProjectMapping = notebookProjectMappingConfig;
                     }
+                    
+                    JsonArray notebookVmOptionsConfig = NotebookUtils.getArgument(c, 6, JsonArray.class);
+                    if (notebookVmOptionsConfig != null) {
```
Comment (sid-srini) [inline nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java:171]: If the vmOptions config value has been emptied (nullifed), shouldn't this field be assigned an empty list?

File: nbcode/notebooks/test/unit/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigsTest.java [hunk 7]
```diff
@@ -173,24 +169,57 @@ public void testGetImplicitImports() {
...
+    /**
+    * Test of getNotebookVmOptions method, of class NotebookConfigs.
+    */
+   @Test
+   public void testGetNotebookVmOptions() {
+       System.out.println("getNotebookVmOptions");
+       try {
+           initialized.get(5, TimeUnit.SECONDS);
+
+           List<String> expResult = configsObj.get(VM_OPTIONS_KEY)
```
Comment (sid-srini) [inline nbcode/notebooks/test/unit/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigsTest.java:183]: Do add a test for when no value is present for the VM_OPTIONS_KEY

File: vscode/package.nls.json [hunk 8]
```diff
@@ -78,6 +78,7 @@
     "jdk.notebook.implicitImports.description": "List of elements to implicitly import in Java notebooks. Defaults to star-imports of java.util, java.io and java.math packages, when empty.",
     "jdk.notebook.implicitImports.markdownDescription": "List of elements to implicitly import in Java notebooks. Defaults to star-imports of `java.util`, `java.io` and `java.math` packages, when empty.",
     "jdk.notebook.projects.mapping.description": "Mapping of Java notebook paths to the path of the project that provides it context.",
+    "jdk.configuration.notebook.vmOptions.description": "The specific JVM options for use in Java notebooks. These options are added in addition to the project configuration, including class-path, module-path, preview features, and added modules.",
```
Comment (sid-srini) [inline vscode/package.nls.json]: nit: `JVM` should be replaced with `Java VM` since that has been used in other setting descriptions.

File: vscode/src/configurations/configuration.ts [hunk 9]
```diff
@@ -37,7 +37,8 @@ export const configKeys = {
     notebookEnablePreview: "notebook.enablePreview",
     notebookImplicitImports: "notebook.implicitImports",
     telemetryEnabled: 'telemetry.enabled',
-    notebookProjectMapping: "notebook.projects.mapping"
+    notebookProjectMapping: "notebook.projects.mapping",
```
Comment (sid-srini) [inline vscode/src/configurations/configuration.ts:39]: nit: Perhaps notebook config keys can be grouped above the telemetryEnabled key. Also, update the copyright header.

File: vscode/package.json [hunk 10]
```diff
@@ -331,6 +331,11 @@
 							"%jdk.configuration.inlay.enabled.enum.var.markdownDescription%"
 						]
 					}
+				},
+				"jdk.notebook.vmOptions": {
+					"description": "%jdk.configuration.notebook.vmOptions.description%",
```
Comment (sid-srini) [inline vscode/package.json]: The key should be similar to other notebook group settings to avoid confusion, i.e. `jdk.notebook.vmOptions.description`.

File: nbcode/notebooks/test/unit/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigsTest.java [hunk 11]
```diff
@@ -173,24 +169,57 @@ public void testGetImplicitImports() {
...
         configsObj.add(ENABLE_PREVIEW_KEY, new JsonPrimitive(false));
+        
         JsonArray addModules = new JsonArray();
         addModules.add(new JsonPrimitive("javafx.controls"));
         addModules.add(new JsonPrimitive("javafx.graphics"));
         configsObj.add(ADD_MODULES_KEY, addModules);
+        
+        JsonArray vmOptions = new JsonArray();
+        vmOptions.add(new JsonPrimitive("--add-opens=java.base/java.lang=ALL-UNNAMED"));
+        vmOptions.add(new JsonPrimitive("--add-opens=java.base/java.util=ALL-UNNAMED"));
```
Comment (sid-srini) [inline nbcode/notebooks/test/unit/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigsTest.java:261]: nit: It may be useful to test a value that contains quoted spaces.
E.g. `"\"-Djava.io.tmpdir=C:\\Temp Folder\\java\""`

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java (hunk 1 above)
Comment (Achal1607) [reply nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java:186]: If we do that and let's say the project jdkhome points to a newer JDK version while the extension’s runtime JDK is older, then JShell will fail to start, because JShell uses the extension’s runtime JDK. 
So, in my opinion it's better to use runtime JDK properties only here.

File: nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java (hunk 6 above)
Comment (Achal1607) [reply nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java:171]: Currently, there won't be any issue since we are restarting the entire LSP server when anyone edits any of the notebook configs, but this issue can occur if in the future instead of reloading the entire LSP server we change the flow.
So, at present all the configs in the notebook follow this pattern due to that I kept it same, but if you want I can refactor this class as part of some other PR?

Comment (Achal1607) [reply nbcode/notebooks/src/org/netbeans/modules/nbcode/java/notebook/NotebookConfigs.java:171]: I have now added the uniform behaviour for every config, so that it sets to default if null is sent by lsp client.

**Review by sid-srini — APPROVED** [review]
Thanks @Achal1607. LGTM 👍
