### PR TITLE
Fixed JDK Downloader windows ARM64 download issue

### LINKED ISSUE #291: Cannot install jdk for windows ARM
Type: <b>Bug</b>

trying to use the JDK downloader to install OpenJDK for windows ARM64 for v21 or v22 will result in a 404 error

Extension version: 22.1.2
VS Code version: Code - Insiders 1.95.0-insider (af6645a661a5402af586154207ee2ea3742f3bea, 2024-10-04T12:46:44.894Z)
OS version: Windows_NT arm64 10.0.26100
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Snapdragon(R) X 12-core X1E80100 @ 3.40 GHz (12 x 2976)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled<br>webnn: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|31.57GB (11.12GB free)|
|Process Argv|--crash-reporter-id 8dc59ac4-06a1-44f4-bf7a-b9a7c128e443|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
vsaa593cf:30376535
py29gd2263:31024238
c4g48928:30535728
vscrp:30624060
962ge761:30841072
pythongtdpath:30726887
welcomedialog:30812478
pythonnoceb:30776497
asynctok:30898717
dsvsc014:30777825
dsvsc015:30821418
pythonmypyd1:30859725
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30870582
dsvsc016:30879898
dsvsc017:30880771
dsvsc018:30880772
cppperfnew:30980852
pythonait:30973460
945dj816:31013170
a69g1124:31018687
dvdeprecation:31040973
dwnewjupyter:31046869
impr_priority:31057980
nativerepl1:31134653
refactort:31084545
pythonrstrctxt:31093868
flighttreat:31119334
wkspc-onlycs-t:31132770
nativeloc1:31118317
wkspc-ranged-t:31151552
cf971741:31144450
e80f6927:31120813
autoexpandse:31146404
i21gd607:31141543
iacca1:31150324
notype1:31143044
showbadge:31139796
f8igb616:31140137

```

</details>

### PR DESCRIPTION
**Pull request by Achal1607**
This PR aims to remove option to download JDK for Windows ARM64 since it is not available.
Closes #291

### CODE REVIEW

File: vscode/src/jdkDownloader/view.ts [hunk 1]
```diff
@@ -234,6 +238,28 @@ export class JdkDownloaderView {
...
+                    const machineArchDropdown = document.getElementById(osDropdownId.replace('OsTypeDropdown', 'MachineArchDropdown'));
+                    
+                    if (osDropdown.value === 'windows') {
+                        machineArchDropdown.innerHTML = '<option value="x64" selected>x64</option>';
+                    } else {
+                        machineArchDropdown.innerHTML = \`
+                            <option value="aarch64" \${machineArchDropdown.value === 'aarch64' ? 'selected' : null}>arm64</option>
+                            <option value="x64" \${machineArchDropdown.value === 'x64' ? 'selected' : null}>x64</option>
+                        \`;
+                    }
```
Comment (sid-srini) [inline vscode/src/jdkDownloader/view.ts:260]: I didn't understand why `getMachineArchHtml()` could not be used here directly.
Some doubts:
1. If a user switches from windows to linux/mac, 
    - Should the dropdown continue to use the previously selected dropdown value? 
    - Its possible that the machine's arch is ARM and so that should be given preference.
2. If a user switches to windows, 
    - then the `getMachineArchHtml` function would handle this appropriately.
3. If a user switches between linux and mac, 
    - then the possibility of the selected OS not being the host's OS is present for both the source and the target OS. 
    - If target OS is the host OS, then we should prefer selecting the host arch. 
    - Else, it is possible that the user wants to maintain the selected arch value. 
    - Should we enhance `getMachineArchHtml` to handle this?
    - IMO perhaps we can just keep it simple and just use the host's arch to make the selection.

**Review by sid-srini — CHANGES_REQUESTED** [review]

File: vscode/src/jdkDownloader/view.ts (hunk 1 above)
Comment (Achal1607) [reply vscode/src/jdkDownloader/view.ts:260]: > * Should the dropdown continue to use the previously selected dropdown value?

IMO user would have chosen something then we should honour that and shouldn't change according to the machine architecture. By default, it is machine architecture. But, if you are not convinced I can change the behaviour no issues.




> * IMO perhaps we can just keep it simple and just use the host's arch to make the selection.

IMO we can at the start keep defaults, and after that let user only do the selection and change part and don't change according to us, it will keep the things simple also.

File: vscode/src/constants.ts [hunk 2]
```diff
@@ -22,7 +22,7 @@ export const ORACLE_JDK_BASE_DOWNLOAD_URL = `https://download.oracle.com/java`;
 export const ORACLE_JDK_DOWNLOAD_VERSIONS = ['23','21'];
 
 export const OPEN_JDK_VERSION_DOWNLOAD_LINKS: { [key: string]: string } = {
-  "23": "https://download.java.net/java/GA/jdk23/3c5b90190c68498b986a97f276efd28a/37/GPL/openjdk-23"
+  "23": "https://download.java.net/java/GA/jdk23.0.1/c28985cbf10d4e648e4004050f8781aa/11/GPL/openjdk-23"
```
[the remark this answers is not in the document]
Comment (Achal1607) [reply vscode/src/constants.ts]: Sorry I missed that, fixed that.

**Review by sid-srini — APPROVED** [review]
Thanks @Achal1607. LGTM.
