### PR TITLE
Fix for delete cache error on windows

### LINKED ISSUE #221: "Delete Oracle Java extension cache for this workspace" fails with an error
Attempting to execute the command says:

image

which seems logical. Red Hat's extension has a similar command and restarts VS Code, most likely to avoid issues like this.

### PR DESCRIPTION
**Pull request by shivam71**
Killed the nb process and the stopped the LSP client so that no process is using the cache  before deleting the directory .
Closed #221

### CODE REVIEW

File: vscode/src/extension.ts [hunk 1]
```diff
@@ -78,7 +78,7 @@ let nbProcess : ChildProcess | null = null;
 let debugPort: number = -1;
 let debugHash: string | undefined;
 let consoleLog: boolean = !!process.env['ENABLE_CONSOLE_LOG'];
-
+let deactivated = false;
```
Comment (Achal1607) [inline vscode/src/extension.ts:81]: Is this flag needed now?

File: vscode/src/extension.ts [hunk 2]
```diff
@@ -514,16 +514,16 @@ export function activate(context: ExtensionContext): VSNetBeansAPI {
...
             if (confirmation === 'Yes') {
-                await fs.promises.rmdir(userDir, {recursive : true});
-                const res = await vscode.window.showInformationMessage('Cache cleared successfully for this workspace', 'Reload window');
-                if (res === 'Reload window') {
-                    await vscode.commands.executeCommand('workbench.action.reloadWindow');
-                }
+                stopClient(client).then(() => killNbProcess(false, log)).then(() => {
+                    fs.promises.rmdir(userDir, {recursive : true});
+                    vscode.commands.executeCommand('workbench.action.reloadWindow')
+                });
```
Comment (Achal1607) [inline vscode/src/extension.ts:526]: Maybe you can add a catch block here for better error handling.

File: vscode/src/extension.ts [hunk 3]
```diff
@@ -514,16 +514,16 @@ export function activate(context: ExtensionContext): VSNetBeansAPI {
             vscode.window.showErrorMessage('Cannot find workspace path');
             return;
         }
+
```
Comment (Achal1607) [inline vscode/src/extension.ts:517]: We can maybe put this block of code in a try catch so that any error can be handled.

**Comment by shivam71** [comment]
Added a callback for error handling

File: vscode/src/extension.ts [hunk 4]
```diff
@@ -514,17 +514,19 @@ export function activate(context: ExtensionContext): VSNetBeansAPI {
...
         if (userDir && fs.existsSync(userDir)) {
-            const confirmation = await vscode.window.showInformationMessage('Are you sure you want to delete cache for this workspace?',
+            const confirmation = await vscode.window.showInformationMessage('Are you sure you want to delete cache for this workspace  and reload the window ?',
                 'Yes', 'Cancel');
             if (confirmation === 'Yes') {
-                await fs.promises.rmdir(userDir, {recursive : true});
-                const res = await vscode.window.showInformationMessage('Cache cleared successfully for this workspace', 'Reload window');
-                if (res === 'Reload window') {
-                    await vscode.commands.executeCommand('workbench.action.reloadWindow');
+                    stopClient(client).then(() => { deactivated=true;
```
Comment (Achal1607) [inline vscode/src/extension.ts:523]: Since the parent function is already using `async/await`, can we refactor this callback-based code to use `async/await` for better consistency? 
This will also allow us to handle errors more effectively using `try/catch` blocks.

File: vscode/src/extension.ts [hunk 5]
```diff
@@ -953,7 +955,7 @@ function doActivateWithJDK(specifiedJDK: string | null, context: ExtensionContex
             if (p == nbProcess && code != 0 && code) {
                 vscode.window.showWarningMessage(`${SERVER_NAME} exited with ` + code);
             }
-            if (stdErr?.match(/Cannot find java/) || os.type() === "Windows_NT" ) {
+            if (stdErr?.match(/Cannot find java/) || (os.type() === "Windows_NT" && !deactivated) ) {
```
Comment (Achal1607) [inline vscode/src/extension.ts:958]: Can we move `"Windows_NT"` to constants file, since it is also used in #251 so that it can be utilized there as well?

**Review by Achal1607 — CHANGES_REQUESTED** [review]

File: vscode/src/extension.ts (hunk 4 above)
Comment (Achal1607) [reply vscode/src/extension.ts:523]: Try to add catch and finally

File: vscode/src/extension.ts [hunk 6]
```diff
@@ -514,17 +514,24 @@ export function activate(context: ExtensionContext): VSNetBeansAPI {
...
-                await fs.promises.rmdir(userDir, {recursive : true});
-                const res = await vscode.window.showInformationMessage('Cache cleared successfully for this workspace', 'Reload window');
-                if (res === 'Reload window') {
-                    await vscode.commands.executeCommand('workbench.action.reloadWindow');
+                    try{
+                        await stopClient(client);
+                        deactivated=true;
+                        await killNbProcess(false,log);
+                        await fs.promises.rmdir(userDir, {recursive : true});
+                        await vscode.window.showInformationMessage("Cache deleted successfully",'Reload window');
```
Comment (Achal1607) [inline vscode/src/extension.ts:528]: nitpick: await not required here in my opinion

File: vscode/src/extension.ts [hunk 7]
```diff
@@ -514,17 +514,24 @@ export function activate(context: ExtensionContext): VSNetBeansAPI {
...
+                    }catch(err){
+                       await  vscode.window.showErrorMessage('Error deleting the cache','Reload window');
```
Comment (Achal1607) [inline vscode/src/extension.ts:530]: nitpick: await not required here in my opinion

File: vscode/src/extension.ts [hunk 8]
```diff
@@ -514,17 +514,24 @@ export function activate(context: ExtensionContext): VSNetBeansAPI {
...
         if (userDir && fs.existsSync(userDir)) {
-            const confirmation = await vscode.window.showInformationMessage('Are you sure you want to delete cache for this workspace?',
+            const confirmation = await vscode.window.showInformationMessage('Are you sure you want to delete cache for this workspace  and reload the window ?',
                 'Yes', 'Cancel');
             if (confirmation === 'Yes') {
-                await fs.promises.rmdir(userDir, {recursive : true});
-                const res = await vscode.window.showInformationMessage('Cache cleared successfully for this workspace', 'Reload window');
-                if (res === 'Reload window') {
-                    await vscode.commands.executeCommand('workbench.action.reloadWindow');
+                    try{
```
Comment (Achal1607) [inline vscode/src/extension.ts:523]: Can you please properly lint this block of code?

**Review by Achal1607 — CHANGES_REQUESTED** [review]

File: vscode/src/extension.ts (hunk 6 above)
Comment (shivam71) [reply vscode/src/extension.ts:528]: If I remove the await then the message may not be shown to the user "Cache deleted successfully" and the window will be reloaded . I tested without the await it doesn't work .

File: vscode/src/extension.ts (hunk 7 above)
Comment (shivam71) [reply vscode/src/extension.ts:530]: Same as above

File: vscode/src/extension.ts (hunk 6 above)
Comment (Achal1607) [reply vscode/src/extension.ts:528]: Sorry, my bad I thought it's just a simple information message, I noticed just now it is user action information message due to that await is required. Sorry, I should have seen in a more diligent way.

**Review by Achal1607 — APPROVED** [review]
LGTM. Thanks @shivam71 for making this change
